version: '3.8'

services:
  # 1. Service Database (Pengganti XAMPP MySQL)
  db:
    image: mysql:8.0
    container_name: diet-app-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: health_app
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      interval: 5s
      retries: 10


  # 2. Service Backend
  backend:
    build: ./backend
    container_name: diet-app-backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=diet-app-db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=health_app
      - JWT_SECRET=rahasia_negara_api_123
    depends_on:
      db:
        condition: service_healthy



  # 3. Service Frontend
# 3. Service Frontend
  frontend:
    build: ./frontend
    container_name: diet-app-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src  # <--- INI JEMBATANNYA
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - WATCHPACK_POLLING=true   # <--- PENTING BUAT WINDOWS AGAR AUTO-RELOAD JALAN
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  db_data: